# Generated by Django 5.1.1 on 2024-09-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gendre",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")],
                default="M",
                max_length=1,
                null=True,
            ),
        ),
    ]
