# Generated by Django 5.1.1 on 2024-09-15 17:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_user_gendre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="name",
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
