# Generated by Django 5.1.1 on 2024-09-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_remove_user_name_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatar.svg", null=True, upload_to="avatars/"
            ),
        ),
    ]
