# Generated by Django 5.1.1 on 2024-09-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_user_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ImageField(null=True, upload_to="post_images/"),
        ),
    ]
