# Generated by Django 5.1.1 on 2024-09-24 19:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_remove_post_images_postimages"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="postimages",
            options={"ordering": ["-image_id"]},
        ),
    ]
