# Generated by Django 5.1.1 on 2024-09-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_images_delete_postimages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.ImageField(null=True, upload_to="images/"),
        ),
    ]
