# Generated by Django 5.1.1 on 2024-09-24 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_alter_images_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="base.post",
            ),
        ),
    ]
