# Generated by Django 5.1.1 on 2024-10-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_alter_images_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="lat",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="lng",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="place_name",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
